### ISSUE TITLE
Blender 3.4.x - Gives an error

### ISSUE THREAD

**Issue by L0wl** [BlenderBoi/Bonera#1]
In Blender ``3.1.x and higher``, the Python interpreter ``was replaced`` from 3.9 to 3.10. The script ``does not work``, giving an error on the ``first`` initiation.

Modules are not imported. Starting from the second one, the import of modules stops working.

### log: ###
``
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\UserName\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\B1\__init__.py", line 12, in <module>
    from . import Bonera_Toolkit_Operators
  File "C:\Users\UserName\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\B1\Bonera_Toolkit_Operators\__init__.py", line 3, in <module>
    from . import Create_Bones_From_Selected
  File "C:\Users\UserName\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\B1\Bonera_Toolkit_Operators\Create_Bones_From_Selected.py", line 2, in <module>
    from Bonera_Toolkit import Utility_Functions
ModuleNotFoundError: No module named 'Bonera_Toolkit'
``

Blender 3.4.1 (Steam)

**Comment by BlenderBoi** [comment]
Hi, the addon in the repo are not plug and play yet (will fix in future), but to fix it, just rename the folder in the zip file from whatever it is to "Bonera_Toolkit" before installing

**Comment by L0wl** [comment]
I have already rewritten the addon, it now works, but it turns out that the error was a little easier to fix
